version: "2"
linters:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - unused
      - linters:
          - staticcheck
        text: "ST1023"
    presets:
      - std-error-handling
